In [2]:
# Importing pandas and numpy, setting display options

import pandas as pd
import numpy as np
pd.set_option("display.max_columns",None)
pd.set_option("display.width",None)
pd.set_option("display.max_colwidth",None)

In [3]:
# Importing/loading all 4 CSV files into pandas dataframes

movies = pd.read_csv("I:\\Prime_Video_Project\\movies.csv")
users = pd.read_csv("I:\\Prime_Video_Project\\users.csv")
watch_history = pd.read_csv("I:\\Prime_Video_Project\\watch_history.csv")
subscription_plans = pd.read_csv("I:\\Prime_Video_Project\\subscription_plans.csv")

In [4]:
# Previewing first 5 rows of movies
movies.head()

,movie_id,title,language,genre,release_year,decade,running_time_minutes,imdb_rating,rating_category,maturity_rating,plot,plot_word_count,is_rating_imputed,is_year_imputed
0,M00001,John Rambo,Tamil,Action,2008,2000s,86,7.0,Good,18+,"In Thailand, John Rambo joins a group of mercenaries to venture into war-torn Burma, and rescue a group of Christian aid workers who were kidnapped by the ruthless local infantry unit.",31,False,False
1,M00002,American Pie,English,Action,1999,1990s,95,7.0,Good,18+,"You'll never look at warm apple pie the same way again! American Pie takes a hysterical look at the goal of four ""unlucky in love"" high school friends who make the ultimate pact: lose their virginity by prom night. Follow the raging hormones of four teenage boys and their girls as they gear up for the most important night of their lives. Sit back and enjoy a piece of America's #1 comedy hit!",73,False,False
2,M00003,Bombshell,English,Drama,2019,2010s,108,6.8,Good,18+,"The provocative real story of three smart, ambitious, strong women who anchored one of America's top news networks-and risked everything to stand up to the man who made them.",29,False,False
3,M00004,Love Birds,Tamil,Romance,1996,1990s,160,5.1,Average,All,"After accidentally meeting, Mridula (Nagma) and Arun (Prabhu Deva) fall in love. However, a few months into their relationship, Arun and Mridhula meet with an accident and he passes away. A devastated Mridula meets a person who looks exactly like her Arun. What happens next is the rest of the movie.",51,False,False
4,M00005,Hippi,Telugu,Romance,2019,2010s,140,5.0,Average,18+,Hippi is about the live-in relationship between an energetic youngster and a confident girl.,14,False,False

In [24]:
# Previewing first 5 rows of movies
users.head()

,user_id,name,age,gender,city,state,plan_id,signup_date,preferred_language,is_active
0,U00001,Anvi Konda,53,Female,Hyderabad,Telangana,P1,2025-02-04,Hindi,True
1,U00002,Gagan Sami,43,Other,Hyderabad,Telangana,P2,2023-06-07,Hindi,True
2,U00003,Tejas Kaul,29,Male,Mumbai,Maharashtra,P1,2022-08-31,Telugu,True
3,U00004,Rushil Saini,57,Other,Pune,Maharashtra,P2,2024-07-23,Telugu,True
4,U00005,Abeer Dutta,22,Male,Guwahati,Assam,P1,2023-06-03,Bengali,True

In [25]:
# Previewing first 5 rows of movies
watch_history.head()

,interaction_id,user_id,movie_id,watch_date,watch_duration_minutes,completed,user_rating,device_type
0,I000001,U00599,M04770,2024-12-23,22,False,5,Laptop
1,I000002,U01957,M00701,2025-06-25,118,True,3,Mobile
2,I000003,U01694,M00532,2025-10-02,157,True,4,Mobile
3,I000004,U01076,M06548,2025-11-12,134,True,5,Tablet
4,I000005,U01617,M05283,2023-05-15,153,True,5,Smart TV

In [26]:
# Previewing first 5 rows of movies
subscription_plans.head()

,plan_id,plan_name,price_inr,billing_cycle,max_screens,video_quality,includes_ads
0,P1,Prime Monthly,299,Monthly,2,HD,False
1,P2,Prime Annual,1499,Yearly,2,HD,False
2,P3,Prime Lite,799,Yearly,1,SD,True
3,P4,Prime Video Mobile Edition,599,Yearly,1,SD,True

In [28]:
#Checking shape (rows, columns) of movies
movies.shape

(8127, 14)

In [29]:
#Checking shape (rows, columns) of users
users.shape

(3000, 10)

In [30]:
#Checking shape (rows, columns) of watch_history
watch_history.shape

(60000, 8)

In [32]:
#Checking shape (rows, columns) of subscription_plans
subscription_plans.shape

(4, 7)

In [33]:
#Checking structure and data types of movies
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 8127 entries, 0 to 8126
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   movie_id              8127 non-null   str
 1   title                 8127 non-null   str
 2   language              8127 non-null   str
 3   genre                 8127 non-null   str
 4   release_year          8127 non-null   int64
 5   decade                8127 non-null   str
 6   running_time_minutes  8127 non-null   int64
 7   imdb_rating           8127 non-null   float64
 8   rating_category       8127 non-null   str
 9   maturity_rating       8127 non-null   str
 10  plot                  8127 non-null   str
 11  plot_word_count       8127 non-null   int64
 12  is_rating_imputed     8127 non-null   bool
 13  is_year_imputed       8127 non-null   bool
dtypes: bool(2), float64(1), int64(3), str(8)
memory usage: 777.9 KB

In [34]:
#Checking structure and data types of uers
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id             3000 non-null   str
 1   name                3000 non-null   str
 2   age                 3000 non-null   int64
 3   gender              3000 non-null   str
 4   city                3000 non-null   str
 5   state               3000 non-null   str
 6   plan_id             3000 non-null   str
 7   signup_date         3000 non-null   str
 8   preferred_language  3000 non-null   str
 9   is_active           3000 non-null   bool
dtypes: bool(1), int64(1), str(8)
memory usage: 214.0 KB

In [35]:
#Checking structure and data types of watch_history
watch_history.info()

<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   interaction_id          60000 non-null  str
 1   user_id                 60000 non-null  str
 2   movie_id                60000 non-null  str
 3   watch_date              60000 non-null  str
 4   watch_duration_minutes  60000 non-null  int64
 5   completed               60000 non-null  bool
 6   user_rating             60000 non-null  int64
 7   device_type             60000 non-null  str
dtypes: bool(1), int64(2), str(5)
memory usage: 3.3 MB

In [36]:
#Checking structure and data types of subscription_plans
subscription_plans.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   plan_id        4 non-null      str
 1   plan_name      4 non-null      str
 2   price_inr      4 non-null      int64
 3   billing_cycle  4 non-null      str
 4   max_screens    4 non-null      int64
 5   video_quality  4 non-null      str
 6   includes_ads   4 non-null      bool
dtypes: bool(1), int64(2), str(4)
memory usage: 328.0 bytes

In [37]:
# Converting Date Columns to Datetime Format
users["signup_date"]=pd.to_datetime(users["signup_date"])

In [38]:
# Confirming signup_date dtype changed to datetime
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id             3000 non-null   str
 1   name                3000 non-null   str
 2   age                 3000 non-null   int64
 3   gender              3000 non-null   str
 4   city                3000 non-null   str
 5   state               3000 non-null   str
 6   plan_id             3000 non-null   str
 7   signup_date         3000 non-null   datetime64[us]
 8   preferred_language  3000 non-null   str
 9   is_active           3000 non-null   bool
dtypes: bool(1), datetime64[us](1), int64(1), str(7)
memory usage: 214.0 KB

In [39]:
# Converting watch_date column to datetime format
watch_history["watch_date"] = pd.to_datetime(watch_history["watch_date"])

In [41]:
# Confirming watch_date dtype changed to datetime
watch_history.info()

<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   interaction_id          60000 non-null  str
 1   user_id                 60000 non-null  str
 2   movie_id                60000 non-null  str
 3   watch_date              60000 non-null  datetime64[us]
 4   watch_duration_minutes  60000 non-null  int64
 5   completed               60000 non-null  bool
 6   user_rating             60000 non-null  int64
 7   device_type             60000 non-null  str
dtypes: bool(1), datetime64[us](1), int64(2), str(4)
memory usage: 3.3 MB

In [45]:
#Descriptive statistics for movies
movies.describe(include="all")

,movie_id,title,language,genre,release_year,decade,running_time_minutes,imdb_rating,rating_category,maturity_rating,plot,plot_word_count,is_rating_imputed,is_year_imputed
count,8127,8127,8127,8127,8127.000000,8127,8127.000000,8127.000000,8127,8127,8127,8127.000000,8127,8127
unique,8127,7261,10,9,NaN,8,NaN,NaN,4,6,7403,NaN,2,2
top,M00001,Flight 192,Hindi,Drama,NaN,2010s,NaN,NaN,Good,13+,An FBI agent has her family taken hostage while she is on a flight to Washington DC. The agent then has to make a decision that could cost the lives of her husband and her son.,NaN,False,False
freq,1,8,1982,3657,NaN,4088,NaN,NaN,4888,2606,8,NaN,6119,7730
mean,NaN,NaN,NaN,NaN,2007.190845,NaN,118.225421,6.340938,NaN,NaN,NaN,43.572659,NaN,NaN
std,NaN,NaN,NaN,NaN,13.221410,NaN,32.064824,1.122775,NaN,NaN,NaN,17.589610,NaN,NaN
min,NaN,NaN,NaN,NaN,1952.000000,NaN,0.000000,1.400000,NaN,NaN,NaN,1.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,2000.000000,NaN,101.000000,5.800000,NaN,NaN,NaN,30.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,2012.000000,NaN,123.000000,6.400000,NaN,NaN,NaN,40.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,2017.000000,NaN,140.000000,7.000000,NaN,NaN,NaN,60.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,2021.000000,NaN,255.000000,9.500000,NaN,NaN,NaN,85.000000,NaN,NaN

In [46]:
#Descriptive statistics for users
users.describe(include="all")

,user_id,name,age,gender,city,state,plan_id,signup_date,preferred_language,is_active
count,3000,3000,3000.00000,3000,3000,3000,3000,3000,3000,3000
unique,3000,2975,NaN,3,20,15,4,NaN,10,2
top,U00001,Ikbal Kothari,NaN,Male,Bhubaneswar,Maharashtra,P2,NaN,Hindi,True
freq,1,2,NaN,1039,168,426,1246,NaN,735,2457
mean,NaN,NaN,39.55300,NaN,NaN,NaN,NaN,2024-07-15 16:45:07.200000,NaN,NaN
min,NaN,NaN,15.00000,NaN,NaN,NaN,NaN,2022-07-16 00:00:00,NaN,NaN
25%,NaN,NaN,27.00000,NaN,NaN,NaN,NaN,2023-07-18 18:00:00,NaN,NaN
50%,NaN,NaN,40.00000,NaN,NaN,NaN,NaN,2024-07-10 12:00:00,NaN,NaN
75%,NaN,NaN,51.00000,NaN,NaN,NaN,NaN,2025-07-11 06:00:00,NaN,NaN
max,NaN,NaN,64.00000,NaN,NaN,NaN,NaN,2026-07-15 00:00:00,NaN,NaN
std,NaN,NaN,14.33426,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
#Descriptive statistics for watch_history
watch_history.describe(include="all")

,interaction_id,user_id,movie_id,watch_date,watch_duration_minutes,completed,user_rating,device_type
count,60000,60000,60000,60000,60000.000000,60000,60000.000000,60000
unique,60000,3000,8117,NaN,NaN,2,NaN,5
top,I000001,U00725,M06870,NaN,NaN,True,NaN,Mobile
freq,1,37,20,NaN,NaN,38930,NaN,23721
mean,NaN,NaN,NaN,2025-07-14 16:53:08.160000,96.949217,NaN,3.237983,NaN
min,NaN,NaN,NaN,2022-07-25 00:00:00,0.000000,NaN,1.000000,NaN
25%,NaN,NaN,NaN,2025-01-01 00:00:00,62.000000,NaN,3.000000,NaN
50%,NaN,NaN,NaN,2025-10-15 00:00:00,105.000000,NaN,3.000000,NaN
75%,NaN,NaN,NaN,2026-04-10 00:00:00,132.000000,NaN,4.000000,NaN
max,NaN,NaN,NaN,2026-07-15 00:00:00,255.000000,NaN,5.000000,NaN
std,NaN,NaN,NaN,NaN,44.239083,NaN,0.975344,NaN

In [49]:
#Descriptive statistics for subscription_plans
subscription_plans.describe(include="all")

,plan_id,plan_name,price_inr,billing_cycle,max_screens,video_quality,includes_ads
count,4,4,4.000000,4,4.00000,4,4
unique,4,4,NaN,2,NaN,2,2
top,P1,Prime Monthly,NaN,Yearly,NaN,HD,False
freq,1,1,NaN,3,NaN,2,2
mean,NaN,NaN,799.000000,NaN,1.50000,NaN,NaN
std,NaN,NaN,509.901951,NaN,0.57735,NaN,NaN
min,NaN,NaN,299.000000,NaN,1.00000,NaN,NaN
25%,NaN,NaN,524.000000,NaN,1.00000,NaN,NaN
50%,NaN,NaN,699.000000,NaN,1.50000,NaN,NaN
75%,NaN,NaN,974.000000,NaN,2.00000,NaN,NaN
max,NaN,NaN,1499.000000,NaN,2.00000,NaN,NaN

In [51]:
#Checking missing values in movies
movies.isnull().sum()

movie_id                0
title                   0
language                0
genre                   0
release_year            0
decade                  0
running_time_minutes    0
imdb_rating             0
rating_category         0
maturity_rating         0
plot                    0
plot_word_count         0
is_rating_imputed       0
is_year_imputed         0
dtype: int64

In [52]:
#Checking missing values in users
users.isnull().sum()

user_id               0
name                  0
age                   0
gender                0
city                  0
state                 0
plan_id               0
signup_date           0
preferred_language    0
is_active             0
dtype: int64

In [53]:
#Checking missing values in watch_history
watch_history.isnull().sum()

interaction_id            0
user_id                   0
movie_id                  0
watch_date                0
watch_duration_minutes    0
completed                 0
user_rating               0
device_type               0
dtype: int64

In [54]:
#Checking missing values in subscription_plans
subscription_plans.isnull().sum()

plan_id          0
plan_name        0
price_inr        0
billing_cycle    0
max_screens      0
video_quality    0
includes_ads     0
dtype: int64

In [56]:
# Checking duplicate rows in movies
movies.duplicated().sum()

np.int64(0)

In [57]:
# Checking duplicate rows in users
users.duplicated().sum()

np.int64(0)

In [58]:
# Checking duplicate rows in watch_history
watch_history.duplicated().sum()

np.int64(0)

In [59]:
# Checking duplicate rows in subscription_plans
subscription_plans.duplicated().sum()

np.int64(0)

In [78]:
# Check for unrealistic age values
users[(users["age"] < 15) | (users["age"] > 100)]

Empty DataFrame
Columns: [user_id, name, age, gender, city, state, plan_id, signup_date, preferred_language, is_active]
Index: []

In [79]:
# Counting how many unrealistic age values exist
((users["age"] < 15) | (users["age"] > 100)).sum()

np.int64(0)

In [80]:
# Viewing movies column names for reference
movies.columns

Index(['movie_id', 'title', 'language', 'genre', 'release_year', 'decade',
       'running_time_minutes', 'imdb_rating', 'rating_category',
       'maturity_rating', 'plot', 'plot_word_count', 'is_rating_imputed',
       'is_year_imputed'],
      dtype='str')

In [82]:
# Check for invalid IMDb ratings (outside 0-10 range)
movies[(movies["imdb_rating"]<0) |  (movies["imdb_rating"]>10)]

Empty DataFrame
Columns: [movie_id, title, language, genre, release_year, decade, running_time_minutes, imdb_rating, rating_category, maturity_rating, plot, plot_word_count, is_rating_imputed, is_year_imputed]
Index: []

In [84]:
# Counting how many invalid IMDb ratings exist
((movies["imdb_rating"]<0) |  (movies["imdb_rating"]>10)).sum()

np.int64(0)

In [85]:
# Viewing users column names for reference
users.columns

Index(['user_id', 'name', 'age', 'gender', 'city', 'state', 'plan_id',
       'signup_date', 'preferred_language', 'is_active'],
      dtype='str')

In [86]:
# Viewing watch_history column names for reference
watch_history.columns

Index(['interaction_id', 'user_id', 'movie_id', 'watch_date',
       'watch_duration_minutes', 'completed', 'user_rating', 'device_type'],
      dtype='str')

In [8]:
# Check for invalid user_rating values (outside 0-5 range)
watch_history[(watch_history["user_rating"]<0) | (watch_history["user_rating"]>5)]

Empty DataFrame
Columns: [interaction_id, user_id, movie_id, watch_date, watch_duration_minutes, completed, user_rating, device_type]
Index: []

In [96]:
# Counting how many invalid user_rating values exist
((watch_history["user_rating"]<0) | (watch_history["user_rating"]>1)).sum()

np.int64(0)

In [116]:
# Referential integrity check: watch_history user_id not present in users
watch_history[~watch_history["user_id"].isin(users["user_id"])]

Empty DataFrame
Columns: [interaction_id, user_id, movie_id, watch_date, watch_duration_minutes, completed, user_rating, device_type]
Index: []

In [117]:
# Counting how many watch_history rows have an unknown user_id
(~watch_history["user_id"].isin(users["user_id"])).sum()

np.int64(0)

In [118]:
#Referential integrity check: watch_history movie_id not present in movies
watch_history[~watch_history["movie_id"].isin(movies["movie_id"])]

Empty DataFrame
Columns: [interaction_id, user_id, movie_id, watch_date, watch_duration_minutes, completed, user_rating, device_type]
Index: []

In [119]:
# Counting how many watch_history rows have an unknown movie_id
(~watch_history["movie_id"].isin(movies["movie_id"])).sum()

np.int64(0)

In [121]:
# Referential integrity check: users plan_id not present in subscription_plans
users[~users["plan_id"].isin(subscription_plans["plan_id"])]

Empty DataFrame
Columns: [user_id, name, age, gender, city, state, plan_id, signup_date, preferred_language, is_active]
Index: []

In [123]:
# Counting how many users have an unknown plan_id
(~users["plan_id"].isin(subscription_plans["plan_id"])).sum()

np.int64(0)

In [125]:
# Saving cleaned movies, users, watch_history, and subscription_plans data back to CSV
movies.to_csv("I:\\Prime_Video_Project\\movies.csv",index=False)
users.to_csv("I:\\Prime_Video_Project\\users.csv",index=False)
watch_history.to_csv("I:\\Prime_Video_Project\\watch_history.csv",index=False)
subscription_plans.to_csv("I:\\Prime_Video_Project\\subscription_plans.csv",index=False)